name: Inline Shell Commands

# on:
#   schedule:
#     - cron: '0 5 * * *'
#   workflow_dispatch:

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-commands:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
      options: --privileged
    
    steps:
      - name: Install git
        run: |
          apt-get update
          apt-get install -y git

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl wget bash procps lsof netcat unzip python3 python3-requests jq

      - name: Debug directory
        run: |
          echo "PWD: $PWD"
          ls -la
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          test -d .git && echo ".git exists" || echo ".git missing"

      - name: Run application
        run: |
          set -e
          cd "$GITHUB_WORKSPACE"
          git status